import Head from "next/head";
import Image from "next/image";
import react from "react";
import Slider from "react-slick";
import Link from "next/link";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import styles from "../styles/Home.module.scss";
export default function Home() {
  const settings = {
    dots: false,
    infinite: true,
    fade: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 4000,
    cssEase: "linear",
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <div className={styles.mainSection}>
        <Slider {...settings}>
          <div className={styles.slide}>
            <Image
              src="/slider1.jpg"
              className={styles.image}
              height={500}
              width={1000}
              alt="person"
              layout="responsive"
            />
          </div>
          <div className={styles.slide}>
            <Image
              src="/slider2.jpg"
              className={styles.image}
              height={500}
              width={1000}
              alt="person"
              layout="responsive"
            />
          </div>
          <div className={styles.slide}>
            <Image
              src="/slider3.jpg"
              className={styles.image}
              height={500}
              width={1000}
              alt="person"
              layout="responsive"
            />
          </div>
          <div className={styles.slide}>
            <Image
              src="/slider4.jpg"
              className={styles.image}
              height={500}
              width={1000}
              alt="person"
              layout="responsive"
            />
          </div>
          <div className={styles.slide}>
            <Image
              src="/slider5.jpg"
              className={styles.image}
              height={500}
              width={1000}
              alt="person"
              layout="responsive"
            />
          </div>
        </Slider>
        <div className={styles.cards}>
          <div className={styles.card}>
            <Image
              src="/p1.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product1">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p2.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product2">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p3.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product3">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p4.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product4">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p5.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product5">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p6.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product{" "}
                some description of the product some description of the product{" "}
                some description of the product{" "}
              </p>
              <Link href="/product6">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p7.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product
                some description of the product some description of the product
                some description of the product
              </p>
              <Link href="/product7">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p8.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product
                some description of the product some description of the product
                some description of the product
              </p>
              <Link href="/product8">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p9.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product
                some description of the product some description of the product
                some description of the product
              </p>
              <Link href="/product9">
                <a>Read more</a>
              </Link>
            </div>
          </div>
          <div className={styles.card}>
            <Image
              src="/p10.jpg"
              height={400}
              width={600}
              alt="person"
              layout="responsive"
            />
            <div className={styles.cardBody}>
              <h3>Title of the product</h3>
              <p>
                some description of the productsome description of the product
                some description of the product some description of the product
                some description of the product
              </p>
              <Link href="/product10">
                <a>Read more</a>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
